FROM python:3.11-slim

WORKDIR /hub

COPY . /hub

RUN mkdir -p /hub/plugins
COPY plugins/auth_plugin.py /hub/plugins/auth_plugin.py

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]