services:
  listener:
    image: x0backslash0x/poc_device-discovery:v1.2
    # output buffering zodat prints sneller in service logs te zien zijn
    command: ["python", "-u", "device-listener.py", "0.0.0.0", "4002", "15"]
    networks:
      - discovery-net
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  announcer:
    image: x0backslash0x/poc_device-discovery:v1.2
    # output buffering zodat prints sneller in service logs te zien zijn
    command: ["python", "-u", "announcer.py", "listener", "4002", "1"]
    depends_on:
      - listener
    networks:
      - discovery-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on_failure

networks:
  discovery-net:
    driver: overlay
    attachable: true
